### PR TITLE
Updated random forest model

### PR DESCRIPTION
**Pull request by notedwin**

### CODE REVIEW

**Review by vingkan — CHANGES_REQUESTED** [review]
I checked out your branch and ran the server to see if things run as expected, since we do not have an automated test. Please fix the issue with model edwin_rf_15 (or let me know if you want to delete this model from production), then we can merge this PR in and deploy.

Review comments about production:
- Default model (edwin_rf_12) seems to work fine!
- Your other model (edwin_rf_15) breaks when requesting XG for a match, see the stack trace at the end of my comment. Maybe you overwrote it with a model that has different features? I couldn't tell from your notebooks which cell writes this file. We can also delete this model completely if you no longer want it to be in production.

Review comments not about production (you don't have to fix these in this PR):
- Nice work with the visualizations for feature importances and SHAP values!
- There are some errors in the visualizations notebook.

Stack trace for the error with model edwin_rf_15 is below. To reproduce this (and to test if you fixed it):

1. Start the server (`python3 server/__init__.py`)
2. Go to `http://localhost:5000/xgtimeplot/-MS6UorLl3PmR-TBwGM9.png`
3. See the error code 500 with stack trace in the Flask process, or see that it returned code 200.

```
127.0.0.1 - - [28/Jan/2021 00:33:35] "GET /xgtimeplot/-MS6UorLl3PmR-TBwGM9.png?clf=edwin_rf_12 HTTP/1.1" 200 -
[2021-01-28 00:33:45,877] ERROR in app: Exception on /xg/-MS6UorLl3PmR-TBwGM9 [GET]
Traceback (most recent call last):
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server/__init__.py", line 188, in get_xg
    match_xg = pred(inflate_match(packed), stadium, gen, clf)
  File "./haxml/prediction.py", line 144, in predict_xg_edwin
    d_kicks["xg"] = clf.predict_proba(d_kicks[features])[:,1]
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 674, in predict_proba
    X = self._validate_X_predict(X)
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 422, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/sklearn/tree/_classes.py", line 403, in _validate_X_predict
    reset=False)
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/sklearn/base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/Users/vineshkannan/Documents/GitHub/haxml/venv/lib/python3.6/site-packages/sklearn/base.py", line 366, in _check_n_features
    f"X has {n_features} features, but {self.__class__.__name__} "
ValueError: X has 8 features, but DecisionTreeClassifier is expecting 9 features as input.
127.0.0.1 - - [28/Jan/2021 00:33:45] "GET /xg/-MS6UorLl3PmR-TBwGM9?clf=edwin_rf_15 HTTP/1.1" 500 -
```

**Comment by notedwin** [comment]
I swapped out my rf-15 model with a rf-8 and made the appropriate changes in the server configuration.
I fixed errors in the notebooks and cleaned up the structure of the repo a bit.

**Review by vingkan — CHANGES_REQUESTED** [review]
Awesome, the two models work smoothly now. Good work changing the server config for the new model.

However, moving the notebooks into the subfolder `/edwins-notebooks` causes the code in your notebooks to break because of the import structure. This is a consequence of how I structured the codebase. Some of the ways it breaks the notebooks:

- Imports for our `haxml` methods won't work, because those are imported relative to the directory that contains the notebooks.
- Loading match data with the `make_df()` fails because those files are loaded from input file paths relative to the directory that contains the notebooks.
- Saving models with joblib fails because the output file paths are also relative to the current directories.

If more people were working on this codebase, there are a couple of ways we could address this, such as, but not limited to:

- Using absolute paths instead of relative paths (pro: works no matter the directory, con: more verbose and can break in other ways).
- Changing the relative paths to reflect that we are now one directory lower (pro: the notebook can still work as usual, con: when we write or run a notebook, we have to remember what directory level it is at and moving it can cause breakages, we can't as easily copy examples between code at different levels).
- Creating more directories like `/notebooks` at the root of the project (pro: can separate these without worrying about paths, con: clogs up the root directory).

For simplicity, I designed the codebase this way so that all the code, our custom modules, our notebooks, and our server, would all be importing from the same level: one directory below the root directory. But you can see how, as the codebase grows, how this can cause issues.

Since this is a smaller project, I would recommend that instead of subfolders, you add the prefix `edwin_` in front of your notebook names. That will give us some organization, and not require any pathing changes. Don't worry about renaming the notebooks that you didn't create. Later, I can rename the shared notebooks with the prefix `general_` or `vinesh_` and Lynn can take care of renaming her notebooks.

I was thinking we could do this simple short-term fix for now so that we can check in your pull request and deploy the new models. Let me know if you have other ideas on how to handle this and we could work on it in a future pull request, but some people find these pathing issues a bit boring, so I wanted to give some more background and not have you bothered with doing more code cleanup work on it.

**Comment by notedwin** [comment]
You are totally correct, you mentioned this before. I don't have any additional solution that doesn't come with cons. In the latest commit, I moved all the files back and added a prefix to them.

**Review by vingkan — APPROVED** [review]

**Comment by vingkan** [comment]
Deploy was successful and the new models in production appear to be working fine!

**Pull request merged**
